import paypalLogo from "./paypalLogo.png";
import emptyCart from "./emptyCart.png";
import paypalIcon from "./icons/paypal-icon.png";
import zelleIcon from "./icons/zelle-icon.png";
import cashappIcon from "./icons/cashapp-icon.png";
import bitcoinIcon from "./icons/bitcoin-icon.png";
import banner_1 from "./banner/banner_1.png";
import exoticBanner1 from "./banner/exotic-pet-store-banner-1.jpg";
import exoticBanner2 from "./banner/exotic-pet-store-banner-2.jpg";
import exoticBanner3 from "./banner/exotic-pet-store-banner-3.jpg";
import exoticPetsLogo from "./icons/exotic-pets-logo.png";
import axolotlCare from "./banner/axolotl-care-sheet.jpg";
import ballPythonCare from "./banner/ball-python-care-sheet.jpg";
import beardedDragonCare from "./banner/bearded-dragon-care-sheet.jpg";
import bloodPythonCare from "./banner/blood-python-care-sheet.jpg";
import crestedGeckoCare from "./banner/crested-gecko-care-sheet.jpg";
import deguCare from "./banner/degu-care-sheet.jpg";
import forestScorpionCare from "./banner/forest-scorpion-care-sheet.jpg";
import greenSnakeCare from "./banner/green-snake-care-sheet.jpg";
import hamsterCare from "./banner/hamster-care-sheet.jpg";
import jacksonChameleonCare from "./banner/jackson-chameleon-care-sheet.jpg";
import prairieDogsCare from "./banner/prairie-dogs-care-sheet.jpg";
import skunksCare from "./banner/skunks-care-sheet.jpg";
import sugarGliderCare from "./banner/sugar-glider-care-sheet.jpg";
import tarantulaSpiderCare from "./banner/tarantula-spider-care-sheet.jpg";
import waterMonitorCare from "./banner/water-monitor-care-sheet.jpg";
import woodTurtleCare from "./banner/wood-turtle-care-sheet.jpg";
import bankTransfer from "./banner/bank-transfer.jpg";
import cashApp from "./banner/cash-app.jpg";
import sendPaypal from "./banner/send-paypal.jpg";
import zellePay from "./banner/zelle-pay.jpg";
import smallExoticPetsSale from "./banner/small-exotic-pets-sale.jpg";
import eaBackground from "./sections/ea-background.jpg";
import exoticAnimalsRanch from "./sections/exotic-animals-ranch.jpg";
import exoticAnimalsTexas from "./sections/exotic-animals-texas.jpg";
import exoticPetBreeder from "./sections/exotic-pet-breeder.jpg";
import guineaPigPremium from "./sections/guinea-pig-premium.jpg";
import axolotlExclusive from "./sections/baby-axolotl-for-sale.jpg";
import bestExoticPets from "./sections/best-exotic-pets.jpg";
import exoticPetAdoption from "./sections/exotic-pet-adoption.jpg";
import exoticPetStore from "./sections/exotic-pet-store.jpg";
import exoticPetFeeders from "./sections/exotic-pet-feeders.jpg";
import exoticPetCare from "./sections/exotic-pet-care.jpg";
import exoticPetsRanch from "./sections/exotic-pets-ranch.jpg";
import drRachel1 from "./sections/dr-rachel-exotic-pet-vets.jpg";
import drRachel2 from "./sections/dr-rachel-exotic-pet-vet.jpg";
import axolotlLitter from "./sections/baby-axolotl-litter.png";
import leopardGeckoLitter from "./sections/baby-leopard-gecko-litter.png";
import hedgehogLitter from "./sections/baby-hedgehog-litter.png";
import prarieDogLitter from "./sections/baby-prairie-dog-litter.png";
import savannahCatLitter from "./sections/savannah-kitten-litter.png";
import fennecFoxLitter from "./sections/baby-fennec-fox-litter.png";
import ballPythonLitter from "./sections/baby-ball-python-litter.png";
import adoptAxolotls from "./categories/adopt-axolotls.jpg";
import adoptCoatimundis from "./categories/adopt-coatimundis.jpg";
import adoptHoofstock from "./categories/adopt-cows-hoofstock.jpg";
import adoptFennecFoxes from "./categories/adopt-fennec-bat-eared-foxes.jpg";
import adoptGeckos from "./categories/adopt-geckos.jpg";
import adoptHedgehogs from "./categories/adopt-hedgehogs.jpg";
import adoptWallabies from "./categories/adopt-kangaroos-wallabies.jpg";
import adoptLemurs from "./categories/adopt-lemurs.jpg";
import adoptMarmoset from "./categories/adopt-marmoset-monkeys.jpg";
import adoptPrarieDogs from "./categories/adopt-prairie-dogs-capybaras.jpg";
import adoptPorcupines from "./categories/adopt-prehensile-porcupines.jpg";
import adoptSavannahCat from "./categories/adopt-savannah-cat.jpg";
import adoptSkunks from "./categories/adopt-skunks-weasels.jpg";
import adoptSnakes from "./categories/adopt-snakes-pythons.jpg";
import adoptSugarGliders from "./categories/adopt-sugar-gliders.jpg";
import adoptTurtles from "./categories/adopt-turtles.jpg";


export { paypalLogo, paypalIcon, zelleIcon, cashappIcon, bitcoinIcon,  bankTransfer, cashApp, sendPaypal, zellePay, emptyCart, banner_1, exoticBanner1, exoticBanner2, exoticBanner3, axolotlCare, ballPythonCare, beardedDragonCare, bloodPythonCare, crestedGeckoCare, deguCare, forestScorpionCare, greenSnakeCare, hamsterCare, jacksonChameleonCare, prairieDogsCare, skunksCare, sugarGliderCare, tarantulaSpiderCare, waterMonitorCare, woodTurtleCare, smallExoticPetsSale, exoticPetsLogo, eaBackground, exoticAnimalsRanch, exoticAnimalsTexas, exoticPetBreeder, guineaPigPremium, axolotlExclusive, bestExoticPets, exoticPetCare, exoticPetFeeders, exoticPetStore, exoticPetAdoption, exoticPetsRanch, drRachel1, drRachel2, leopardGeckoLitter, axolotlLitter, hedgehogLitter, prarieDogLitter, savannahCatLitter, fennecFoxLitter, ballPythonLitter, adoptAxolotls, adoptCoatimundis, adoptHoofstock, adoptFennecFoxes, adoptGeckos, adoptHedgehogs, adoptWallabies, adoptLemurs, adoptMarmoset, adoptPrarieDogs, adoptPorcupines, adoptSavannahCat, adoptSkunks, adoptSnakes, adoptSugarGliders, adoptTurtles };


// ================== Adoption Data ==================

import boxRedEaredTurtles from "./categories/box-albino-red-eared-turtles-for-sale.jpg";
import capybarasPrairieDogs from "./categories/capybaras-prairie-dogs-for-sale.jpg";
import cornSnakesBallPythons from "./categories/corn-snakes-ball-pythons-for-sale.jpg";
import fennecBatEaredFoxPups from "./categories/fennec-fox-pups-for-sale.jpg";
import HighparkHoofstock from "./categories/highpark-calves-baby-goats-hoofstock-for-sale.jpg";
import crestedLeopardGeckos from "./categories/leopard-crested-geckos-for-sale.jpg";
import platinumSugarGliders from "./categories/platinum-sugar-gliders-for-sale.jpg";
import pygmyMarmosetMonkey from "./categories/pygmy-marmoset-finger-monkeys-for-sale.jpg";
import prehensileTailedPorcupine from "./categories/quilliam-prehensile-tailed-porcupine-baby.jpg";
import ringTailedCoati from "./categories/ring-tailed-coati-cub-for-sale.jpg";
import hamstersHedgehogs from "./categories/rodents-hedgehogs-for-sale.jpg";
import hybridSavannahKittens from "./categories/serval-hybrid-f4-savannah-kittens.jpg";
import skunksFerretsWeasels from "./categories/skunks-and-ferrets-for-sale.jpg";
import triColorLemurs from "./categories/tri-color-ring-tailed-lemurs-for-sale.jpg";
import bennetsWallaby from "./categories/yellow-footed-rock-wallaby-for-sale.jpg";

export { boxRedEaredTurtles, capybarasPrairieDogs, cornSnakesBallPythons, fennecBatEaredFoxPups, HighparkHoofstock, crestedLeopardGeckos, platinumSugarGliders, pygmyMarmosetMonkey, prehensileTailedPorcupine, ringTailedCoati, hamstersHedgehogs, hybridSavannahKittens, skunksFerretsWeasels, triColorLemurs, bennetsWallaby };

import adoptLeucisticAxolotl from "./products/axolotls/gfp-leucistic-axolotl.webp";
import adoptCopperAxolotl from "./products/axolotls/copper-axolotl-for-sale.webp";
import adoptSugarGlider from "./products/mammals/female-sugar-glider-for-sale.jpg";
import adoptSugarGlider2 from "./products/mammals/adult-male-sugar-glider.jpg";
import adoptFennecFox from "./products/mammals/baby-fennec-fox-registered.jpg";
import adoptRingTaillemur from "./products/mammals/baby-ring-tailed-lemur.jpg";
import adoptF5SavannahCat from "./products/mammals/f5-savannah-kittens-for-sale.jpg";
import adoptFemaleSavannahCat from "./products/mammals/female-savannah-kitten-for-sale.jpg";
import adoptPygmyMarmoset from "./products/mammals/pygmy-marmoset-monkey-for-sale.jpg";
import adoptBabyCoati from "./products/mammals/baby-coati-for-sale.jpg";
import adoptPrehensilePorcupine from "./products/mammals/prehensile-tailed-porcupine-baby.jpg";
import adoptStripedWeasel from "./products/mammals/libyan-striped-weasel-for-sale.jpg";
import adoptHighparkBull from "./products/hoofstock/micro-highpark-bull-for-sale.jpg";
import adoptBabyCapybaras from "./products/mammals/baby-capybaras-for-sale.jpg";
import adoptBabyPrairieDog from "./products/mammals/prairie-dog-baby.jpg";
import adoptBoxTurtle from "./products/turtles/baby-box-turtle-for-sale.jpg";
import adoptSliderTurtle from "./products/turtles/red-eared-slider-turtle-for-sale.jpg";
import adoptBabyleopardGecko from "./products/geckos/baby-crested-gecko-for-sale.jpg";
import adoptBabyCrestedGecko from "./products/geckos/baby-leopard-gecko-for-sale.jpg";
import adoptBabyPygmyHedgehog from "./products/mammals/buy-pygmy-hedgehogs.jpg";
import adoptBabyDwarfHamster from "./products/mammals/baby-dwarf-hamster-for-sale.jpg";
import adoptBabyWallaby from "./products/mammals/baby-wallaby-for-sale.jpg";
import adoptRedNeckWallaby from "./products/mammals/red-necked-wallaby-baby-for-sale.jpg";
import adoptAlbinoCornSnake from "./products/snakes/albino-striped-corn-snake-baby.jpg";
import adoptPastelBallPython from "./products/snakes/pastel-ball-python-for-sale.jpg";



export { adoptLeucisticAxolotl, adoptCopperAxolotl, adoptSugarGlider, adoptSugarGlider2, adoptFennecFox, adoptRingTaillemur, adoptF5SavannahCat, adoptFemaleSavannahCat, adoptPygmyMarmoset, adoptBabyCoati, adoptPrehensilePorcupine, adoptStripedWeasel, adoptHighparkBull, adoptBabyCapybaras, adoptBabyPrairieDog, adoptBoxTurtle, adoptSliderTurtle, adoptBabyleopardGecko, adoptBabyCrestedGecko, adoptBabyPygmyHedgehog, adoptBabyDwarfHamster, adoptBabyWallaby, adoptRedNeckWallaby, adoptAlbinoCornSnake, adoptPastelBallPython,  };